warning_threshold: 200

excluded:
 - Pods

disabled_rules:
  - variable_name
  - cyclomatic_complexity
  - large_tuple
  - trailing_whitespace
  - force_try
  - force_cast
  - function_body_length
  - line_length
  - type_body_length
  - multiple_closures_with_trailing_closure
  - redundant_string_enum_value
  - inert_defer
  - nesting
  - type_name
  - file_length

line_length:
  warning: 250
  error: 500

function_parameter_count:
  warning: 8
  error: 15

file_length:
  warning: 500

type_body_length:
  warning: 400
  error: 450
